#!/bin/bash

# Build docker image
git clone https://github.com/brianmaxon/dokku-postgis-dockerfiles /tmp/dokku-postgis-dockerfiles
docker build -q=true -t brianmaxon/postgresql /tmp/dokku-postgis-dockerfiles
rm -rf /tmp/dokku-postgis-dockerfiles
